name: Notify Codex Persona on PR Update

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  notify-codex-persona:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Codex Persona webhook
      run: |
        curl -X POST "https://codex-persona.vercel.app/webhook" \
        -H "Content-Type: application/json" \
        -d '{
          "repository": {"full_name": "${{ github.repository }}"},
          "pull_request": {"number": ${{ github.event.pull_request.number }}}
        }'
